apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: miphp
    namespace: harness-delegate-ng
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: miphp
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: miphp
      spec:
        containers:
        - image: mguazzardo/miphp:v2
          imagePullPolicy: IfNotPresent
          name: miphp
kind: List
metadata:
  resourceVersion: ""
